import {artURL} from './art';
import {Worksheet} from './worksheet';
import {decimal,numberText} from './math';
import {kindLabel} from './learning';
const shortId=(s:Worksheet)=>s.id.slice(0,8).toUpperCase();
function header(s:Worksheet){return '<header class="ws-header"><div><p class="ws-eyebrow">소수의 성 · 마지막 불꽃</p><h1>오답 풀이 연습 학습지</h1><p class="ws-meta">이름 ______________  4학년 ___반 ___번 · '+new Date(s.createdAt).toLocaleDateString('ko-KR')+'</p></div><div class="ws-emblem"><span class="ws-guide" aria-hidden="true" style="background-image:url('+artURL('heroes-level-4-v1')+')"></span><span class="ws-egg" aria-hidden="true"></span><b>1 / 1</b></div></header><div class="ws-mission">훈련서 '+shortId(s)+' · 20개의 정답으로 봉인된 돌 알을 깨워라!</div>';}
export function worksheetPages(s:Worksheet){
 const groups=s.groups.map((group,i)=>'<div class="ws-cipher-group"><b>암호 '+(i+1)+'</b><div>'+group.map((n,j)=>(j?'<span>+</span>':'')+'<label><small>'+String(n+1).padStart(2,'0')+'번 룬</small><i></i></label>').join('')+'<span>=</span><label><small>룬의 합</small><i></i></label><span>→</span><label><small>알파벳</small><i></i></label></div></div>').join('');
 const decoder='<div class="ws-map"><h2>01 · 정답 → 룬 숫자 지도</h2><p class="ws-map-note">내 정답에 해당하는 룬 숫자를 찾아 문제 옆에 적어요. 가짜 답도 있어요.</p><div class="ws-decoder">'+s.decoder.map(d=>'<span><b>'+numberText(d.answer)+'</b><i>→</i><strong>'+d.rune+'</strong></span>').join('')+'</div></div>';
 const cipher='<div class="ws-map"><h2>02 · 룬의 합 → 알파벳 표</h2><div class="ws-alphabet">'+Array.from({length:26},(_,i)=>'<span><b>'+i+'</b><strong>'+String.fromCharCode(65+i)+'</strong></span>').join('')+'</div><h2>03 · 20개의 룬으로 여섯 글자 해독하기</h2><p class="ws-map-note">각 문항의 룬을 더하고, 합에 해당하는 알파벳을 찾아요. 룬 0도 합에 포함해요.</p><div class="ws-cipher-groups">'+groups+'</div><div class="ws-final-code"><b>나의 6자리 암호</b>'+Array.from({length:6},()=>'<i></i>').join('')+'</div></div>';
 return '<section class="ws-sheet" aria-label="학습지 1쪽">'+header(s)+'<div class="ws-question-grid">'+s.questions.map((q,i)=>'<article class="ws-question" data-question="'+(i+1)+'"><b class="ws-qnumber">'+String(i+1).padStart(2,'0')+'</b><div class="ws-equation">'+decimal(q.a,q.digits)+' '+(q.operation==='+'?'+':'−')+' '+decimal(q.b,q.digits)+' = <span class="ws-answer"></span></div><label class="ws-rune">룬 <i></i></label></article>').join('')+'</div>'+decoder+cipher+'<footer class="ws-footer"><b>학습지 출력 화면에서 돌 알의 암호를 입력해요.</b><span>sosoo-defence.vercel.app · 훈련서 '+shortId(s)+' · 출력한 같은 브라우저에서 입력해요.</span></footer></section>';
}
export function worksheetFocus(s:Worksheet){return s.focus.length?s.focus.map(kindLabel).join(' / '):'기록이 아직 적어 현재 단계의 기본 유형을 골랐어요.';}
