import {Worksheet,WorksheetQuestion} from './worksheet';
import {decimal,numberText} from './math';
import {kindLabel} from './learning';
const shortId=(s:Worksheet)=>s.id.slice(0,8).toUpperCase();
function header(s:Worksheet,page:number){return '<header class="ws-header"><div><p class="ws-eyebrow">소수의 성 · 마지막 불꽃</p><h1>수호자의 계산 훈련</h1><p class="ws-meta">이름 ______________  4학년 ___반 ___번 · '+new Date(s.createdAt).toLocaleDateString('ko-KR')+'</p></div><div class="ws-emblem"><span class="ws-guide" aria-hidden="true" style="background-image:url(/assets/dungeon/heroes-level-'+([1,4,10][page-1])+'-v1.png)"></span><span class="ws-egg" aria-hidden="true"></span><b>'+page+' / 3</b></div></header><div class="ws-mission">훈련서 '+shortId(s)+' · '+(page===3?'20개의 정답으로 봉인된 돌 알을 깨워라!':'소수점을 맞추고, 같은 자리끼리 계산해 성의 힘을 되찾자!')+'</div>';}
export function questionPrompt(q:WorksheetQuestion){const a=decimal(q.a,q.digits),b=decimal(q.b,q.digits);if(q.context==='money')return q.operation==='-'?'코인 '+a+'에서 타워 가격 '+b+'만큼 썼어요. 남는 코인은 얼마인가요?':'코인 '+a+'에 방어 보상 '+b+'만큼 더했어요. 코인은 모두 얼마인가요?';return q.operation==='+'?'힘이 '+a+'인 성벽 조각과 '+b+'인 조각을 합쳐요. 조각의 힘은 모두 얼마인가요?':'체력이 '+a+'인 돌 몬스터가 공격력 '+b+'의 포탄을 맞으면 체력이 얼마 남나요?';}
export function worksheetPages(s:Worksheet){
 const pages=[0,1].map(page=>'<section class="ws-sheet" aria-label="학습지 '+(page+1)+'쪽">'+header(s,page+1)+'<div class="ws-question-grid">'+s.questions.slice(page*10,page*10+10).map((q,i)=>'<article class="ws-question" data-question="'+(page*10+i+1)+'"><div class="ws-qtop"><b>'+String(page*10+i+1).padStart(2,'0')+'</b><span>'+(q.context==='money'?'타워 제작소':q.context==='wall'?'성벽 공방':'돌 몬스터 방어')+'</span><label>룬 <i></i></label></div><p>'+questionPrompt(q)+'</p><div class="ws-equation">'+decimal(q.a,q.digits)+' '+(q.operation==='+'?'+':'−')+' '+decimal(q.b,q.digits)+' = <span class="ws-answer"></span></div><div class="ws-working" aria-hidden="true"></div></article>').join('')+'</div><footer class="ws-footer"><span>세 자리 소수는 코인 문항에서만 사용해요. 0.3과 0.30은 같은 수예요.</span><b>정답을 구했다면 3쪽 룬 지도에서 작은 숫자를 찾아요.</b></footer></section>');
 const groups=s.groups.map((group,i)=>'<div class="ws-cipher-group"><b>암호 '+(i+1)+'</b><div>'+group.map((n,j)=>(j?'<span>+</span>':'')+'<label><small>'+String(n+1).padStart(2,'0')+'번 룬</small><i></i></label>').join('')+'<span>=</span><label><small>룬의 합</small><i></i></label><span>→</span><label><small>알파벳</small><i></i></label></div></div>').join('');
 pages.push('<section class="ws-sheet ws-map" aria-label="학습지 3쪽 암호 지도">'+header(s,3)+'<ol class="ws-steps"><li>1~20번을 모두 풀어요. 아래 지도에서 <b>내 정답 → 룬 숫자</b>를 찾아 문제 옆에 적어요.</li><li>암호 묶음마다 룬을 더해요. <b>룬의 합 → 알파벳</b> 표에서 글자를 찾아요.</li><li>여섯 글자를 순서대로 게임에 입력하면 무작위 영웅 한 마리를 얻어요.</li></ol><h2>01 · 정답을 룬 숫자로 바꾸기</h2><div class="ws-decoder">'+s.decoder.map(d=>'<span><b>'+numberText(d.answer)+'</b><i>→</i><strong>'+d.rune+'</strong></span>').join('')+'</div><p class="ws-map-note">지도에는 가짜 답도 있어요. 계산한 답과 같은 수를 찾아요. 0도 더할 수 있는 룬이에요.</p><h2>02 · 룬의 합을 알파벳으로 바꾸기</h2><div class="ws-alphabet">'+Array.from({length:26},(_,i)=>'<span><b>'+i+'</b><strong>'+String.fromCharCode(65+i)+'</strong></span>').join('')+'</div><h2>03 · 20개의 룬으로 여섯 글자 해독하기</h2><div class="ws-cipher-groups">'+groups+'</div><div class="ws-final-code"><b>나의 6자리 암호</b>'+Array.from({length:6},()=>'<i></i>').join('')+'</div><footer class="ws-footer"><b>게임 시작 화면 → 암호 입력 · 수집 몬스터</b><span>sosoo-defence.vercel.app · 훈련서 '+shortId(s)+' · 출력한 같은 브라우저에서 입력해요.</span></footer></section>');
 return pages.join('');
}
export function worksheetFocus(s:Worksheet){return s.focus.length?s.focus.map(kindLabel).join(' / '):'기록이 아직 적어 현재 단계의 기본 유형을 골랐어요.';}
