import {artURL} from './art';
import {loadSave} from './save';
import {Worksheet} from './worksheet';
import {getOrCreateWorksheet,loadWorkbook,redeemWorksheet,selectWorksheetHero} from './worksheet-store';
import {worksheetPages,worksheetFocus} from './worksheet-view';
import {collectionHTML,heroRevealHTML} from './collection-ui';
import {heroSpec} from './multiplayer/heroes';
import {importLearningRecords} from './learning';
import {onAuthStateChanged} from 'firebase/auth';
import {auth,requestAccountLogin} from './account-gate';
import {runAccountAction} from './page-access';
import './game.css';
import './collection.css';
import './worksheet.css';
const app=document.getElementById('app')!,params=new URLSearchParams(location.search);let sheet:Worksheet|null=null,busy=false;
const accountUid=auth?.currentUser?.uid??null;let accessRevoked=false;
function hasAccountAccess(){return !accessRevoked&&!!accountUid&&auth?.currentUser?.uid===accountUid;}
function revokeAccess(){if(accessRevoked)return;accessRevoked=true;sheet=null;busy=false;void requestAccountLogin('worksheet').then(()=>location.reload());}
app.innerHTML='<main class="workbook"><header class="workbook-header"><div><p>소수의 성 · 수호자의 훈련소</p><h1>학습지로 돌 알의 봉인을 풀어요</h1></div><a class="workbook-home" href="/">시작 화면</a></header><div class="workbook-toolbar"><button id="ws-print" disabled>이 학습지 다시 인쇄</button><button id="ws-new" disabled>새 학습지 출력</button><button id="ws-collection">내 수집 영웅</button><label>훈련서 선택 <select id="ws-select" disabled></select></label></div><p id="ws-focus"></p><p class="workbook-feedback" id="ws-status" role="status" aria-live="polite">학습 기록으로 문항을 준비하고 있어요…</p><section class="workbook-unlock"><div><p class="ws-eyebrow">20개 정답으로 해독한 여섯 글자</p><h2>돌 알의 암호 입력</h2><p>룬 지도의 암호 1~6을 순서대로 입력해요. 학습지 한 장당 보상은 한 번이에요.</p></div><form id="ws-code-form"><label for="ws-code">6자리 알파벳 암호</label><div><input id="ws-code" name="code" maxlength="6" pattern="[A-Za-z]{6}" placeholder="ABCDEF" autocomplete="off" autocapitalize="characters" spellcheck="false" required disabled><button id="ws-redeem" disabled>돌 알 깨우기</button></div></form></section><div id="ws-pages"></div><div class="workbook-dialog hidden" id="ws-dialog" role="dialog" aria-modal="true" aria-label="수집 영웅"><div class="workbook-card hero-collection-dialog"><button id="ws-close" aria-label="닫기">×</button><div id="ws-dialog-body"></div></div></div></main>';
const $=(id:string)=>document.getElementById(id)!;let previous:HTMLElement|null=null;
function feedback(text:string){if(hasAccountAccess())$('ws-status').textContent=text;}
function render(){if(!hasAccountAccess()||!sheet)return;const book=loadWorkbook();$('ws-pages').innerHTML=worksheetPages(sheet);$('ws-focus').textContent='이번 훈련의 연습 유형 · '+worksheetFocus(sheet);const select=$('ws-select') as HTMLSelectElement;select.replaceChildren();for(const s of [...book.sheets].reverse()){const o=document.createElement('option');o.value=s.id;o.textContent=s.id.slice(0,8).toUpperCase()+' · '+new Date(s.createdAt).toLocaleDateString('ko-KR')+(s.claimedHero?' · 보상 받음':' · 도전 중');o.selected=s.id===sheet.id;select.append(o);}select.disabled=busy;($('ws-print') as HTMLButtonElement).disabled=busy;($('ws-new') as HTMLButtonElement).disabled=busy;($('ws-code') as HTMLInputElement).disabled=busy||!!sheet.claimedHero;($('ws-redeem') as HTMLButtonElement).disabled=busy||!!sheet.claimedHero;
 if(sheet.claimedHero)feedback('이 훈련서는 '+heroSpec(sheet.claimedHero)!.name+'의 보상을 받았어요. 새 학습지를 출력해 다시 도전할 수 있어요.');
 const url=new URL(location.href);url.searchParams.set('id',sheet.id);history.replaceState(null,'',url.href);
}
async function print(){if(!hasAccountAccess()||!sheet)return;feedback('인쇄 창에서 A4 한 쪽을 출력하거나 PDF로 저장하세요. 화면의 도구와 암호 입력란은 인쇄되지 않아요.');const printed=await runAccountAction(hasAccountAccess,[()=>document.fonts.ready,()=>{const egg=new Image();egg.src=artURL('hero-eggs-v1');return egg.decode().catch(()=>{});}],()=>window.print());if(!printed||!hasAccountAccess())return;const url=new URL(location.href);url.searchParams.delete('print');history.replaceState(null,'',url.href);}
function open(html:string){if(!hasAccountAccess())return;previous=document.activeElement as HTMLElement;$('ws-dialog-body').innerHTML=html;$('ws-dialog-body').scrollTop=0;$('ws-dialog').classList.remove('hidden');for(const node of Array.from(document.querySelectorAll<HTMLElement>('.workbook > :not(.workbook-dialog)')))node.inert=true;$('ws-close').focus();}
function close(){if(!hasAccountAccess())return;$('ws-dialog').classList.add('hidden');for(const node of Array.from(document.querySelectorAll<HTMLElement>('.workbook > :not(.workbook-dialog)')))node.inert=false;(previous?.isConnected?previous:$('ws-collection')).focus();}
function collection(){if(!hasAccountAccess())return;open('<p class="ws-eyebrow">훈련으로 깨어난 돌의 영웅</p><h2>내 수집 영웅</h2>'+collectionHTML());bindSelection();}
function bindSelection(){$('ws-dialog-body').querySelectorAll<HTMLButtonElement>('[data-collection-hero]').forEach(b=>b.onclick=async()=>{if(!hasAccountAccess())return;try{await selectWorksheetHero(b.dataset.collectionHero!);collection();}catch(e){feedback((e as Error).message);}});}
async function fresh(){if(!hasAccountAccess()||busy)return;busy=true;render();feedback('최근 학습 기록으로 새 20문항을 만들고 있어요…');try{const prepared=await getOrCreateWorksheet(loadSave().level,true);if(!hasAccountAccess())return;sheet=prepared;($('ws-code') as HTMLInputElement).value='';busy=false;render();await print();}catch(e){busy=false;render();feedback((e as Error).message);}}
$('ws-print').onclick=()=>void print();$('ws-new').onclick=()=>void fresh();$('ws-collection').onclick=collection;$('ws-close').onclick=close;
$('ws-select').onchange=()=>{if(!hasAccountAccess())return;sheet=loadWorkbook().sheets.find(s=>s.id===($('ws-select') as HTMLSelectElement).value)??sheet;($('ws-code') as HTMLInputElement).value='';feedback('선택한 훈련서의 6자리 암호를 입력해요.');render();};
$('ws-code-form').onsubmit=async e=>{e.preventDefault();if(!hasAccountAccess()||!sheet||busy)return;busy=true;render();try{const sheetId=sheet.id,result=await redeemWorksheet(sheetId,($('ws-code') as HTMLInputElement).value);if(!hasAccountAccess())return;sheet=loadWorkbook().sheets.find(s=>s.id===sheetId)!;feedback('암호 해독 성공! '+result.hero.name+'을 얻었어요.');open('<p class="ws-eyebrow">봉인이 풀렸다 · 새로운 동료</p>'+heroRevealHTML(result.hero,result.copies)+'<p class="collection-note">대전을 시작할 때 수집 영웅 하나를 골라 바로 출전해요. 기존 돌 알 부화와 별도로 사용할 수 있어요.</p>');$('ws-equip').onclick=async()=>{if(!hasAccountAccess())return;try{await selectWorksheetHero(result.hero.id);collection();}catch(error){feedback((error as Error).message);}};}catch(error){feedback((error as Error).message);}finally{busy=false;render();}};
$('ws-dialog').onclick=e=>{if(e.target===$('ws-dialog'))close();};$('ws-dialog').addEventListener('keydown',e=>{if(e.key==='Escape')close();else if(e.key==='Tab'){const controls=Array.from($('ws-dialog').querySelectorAll<HTMLButtonElement>('button:not(:disabled)'));const first=controls[0],last=controls.at(-1)!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('storage',e=>{if(hasAccountAccess()&&e.key==='decimal-workbook-v1'&&sheet){sheet=loadWorkbook().sheets.find(s=>s.id===sheet!.id)??sheet;render();}});
async function importCloudLearning(){if(!navigator.onLine||!hasAccountAccess())return;try{const {loadLearningHistory}=await import('./multiplayer/record-store');if(!hasAccountAccess())return;const rows=await loadLearningHistory(accountUid!);if(hasAccountAccess())importLearningRecords(rows);}catch{/* Saved local learning remains available while the cloud is offline. */}}
async function init(){if(!hasAccountAccess()){revokeAccess();return;}try{await importCloudLearning();if(!hasAccountAccess())return;sheet=params.has('id')?loadWorkbook().sheets.find(s=>s.id===params.get('id'))??null:null;if(!sheet){const prepared=await getOrCreateWorksheet(loadSave().level,params.get('print')==='1');if(!hasAccountAccess())return;sheet=prepared;}feedback('연습이 필요한 유형을 중심으로 20문항을 준비했어요. 같은 쪽의 룬 지도와 암호 칸으로 여섯 글자를 해독해요.');render();if(params.get('print')==='1')await print();}catch(e){if(!hasAccountAccess())return;feedback((e as Error).message);($('ws-new') as HTMLButtonElement).disabled=false;}}
const stopAuthWatch=auth?onAuthStateChanged(auth,value=>{if(!value||value.uid!==accountUid)revokeAccess();}):undefined;
window.addEventListener('pagehide',()=>stopAuthWatch?.(),{once:true});
window.addEventListener('beforeprint',()=>{if(!hasAccountAccess())revokeAccess();});
void init();
