import {artURL} from './art';
import {Worksheet,WorksheetQuestion} from './worksheet';
import {decimal,numberText} from './math';
import {kindLabel} from './learning';
const shortId=(s:Worksheet)=>s.id.slice(0,8).toUpperCase();
function header(s:Worksheet,page:number){return '<header class="ws-header"><div><p class="ws-eyebrow">소수의 성 · 마지막 불꽃</p><h1>수호자의 계산 훈련</h1><p class="ws-meta">이름 ______________  4학년 ___반 ___번 · '+new Date(s.createdAt).toLocaleDateString('ko-KR')+'</p></div><div class="ws-emblem"><span class="ws-guide" aria-hidden="true" style="background-image:url('+artURL('heroes-level-'+([1,10][page-1])+'-v1')+')"></span><span class="ws-egg" aria-hidden="true"></span><b>'+page+' / 2</b></div></header><div class="ws-mission">훈련서 '+shortId(s)+' · '+(page===2?'20개의 정답으로 봉인된 돌 알을 깨워라!':'소수점을 맞추고, 같은 자리끼리 계산해 성의 힘을 되찾자!')+'</div>';}
export function questionPrompt(q:WorksheetQuestion){const a=decimal(q.a,q.digits),b=decimal(q.b,q.digits);if(q.context==='money')return q.operation==='-'?'코인 '+a+'에서 타워 가격 '+b+'만큼 썼어요. 남는 코인은 얼마인가요?':'코인 '+a+'에 방어 보상 '+b+'만큼 더했어요. 코인은 모두 얼마인가요?';return q.operation==='+'?'힘이 '+a+'인 성벽 조각과 '+b+'인 조각을 합쳐요. 조각의 힘은 모두 얼마인가요?':'체력이 '+a+'인 돌 몬스터가 공격력 '+b+'의 포탄을 맞으면 체력이 얼마 남나요?';}
export function worksheetPages(s:Worksheet){
 const groups=s.groups.map((group,i)=>'<div class="ws-cipher-group"><b>암호 '+(i+1)+'</b><div>'+group.map((n,j)=>(j?'<span>+</span>':'')+'<label><small>'+String(n+1).padStart(2,'0')+'번 룬</small><i></i></label>').join('')+'<span>=</span><label><small>룬의 합</small><i></i></label><span>→</span><label><small>알파벳</small><i></i></label></div></div>').join('');
 const decoder='<div class="ws-map"><h2>01 · 정답 → 룬 숫자 지도</h2><p class="ws-map-note">1~20번을 풀고, 내 정답에 해당하는 룬 숫자를 찾아 문제 옆에 적어요.</p><div class="ws-decoder">'+s.decoder.map(d=>'<span><b>'+numberText(d.answer)+'</b><i>→</i><strong>'+d.rune+'</strong></span>').join('')+'</div><p class="ws-map-note">가짜 답도 있어요. 0.3과 0.30은 같은 수예요. 룬 0도 합에 포함해요.</p></div>';
 const cipher='<div class="ws-map"><h2>02 · 룬의 합 → 알파벳 표</h2><div class="ws-alphabet">'+Array.from({length:26},(_,i)=>'<span><b>'+i+'</b><strong>'+String.fromCharCode(65+i)+'</strong></span>').join('')+'</div><h2>03 · 20개의 룬으로 여섯 글자 해독하기</h2><p class="ws-map-note">1쪽 지도에서 찾은 룬들을 더해요. 위 표에서 합에 해당하는 알파벳을 찾아요.</p><div class="ws-cipher-groups">'+groups+'</div><div class="ws-final-code"><b>나의 6자리 암호</b>'+Array.from({length:6},()=>'<i></i>').join('')+'</div></div>';
 const pages=[0,1].map(page=>'<section class="ws-sheet" aria-label="학습지 '+(page+1)+'쪽">'+header(s,page+1)+'<div class="ws-question-grid">'+s.questions.slice(page*10,page*10+10).map((q,i)=>'<article class="ws-question" data-question="'+(page*10+i+1)+'"><div class="ws-qtop"><b>'+String(page*10+i+1).padStart(2,'0')+'</b><span>'+(q.context==='money'?'타워 제작소':q.context==='wall'?'성벽 공방':'돌 몬스터 방어')+'</span><label>룬 <i></i></label></div><p>'+questionPrompt(q)+'</p><div class="ws-equation">'+decimal(q.a,q.digits)+' '+(q.operation==='+'?'+':'−')+' '+decimal(q.b,q.digits)+' = <span class="ws-answer"></span></div><div class="ws-working" aria-hidden="true"></div></article>').join('')+'</div>'+(page===0?decoder:cipher)+'<footer class="ws-footer">'+(page===0?'<span>세 자리 소수는 코인 문항에서만 사용해요.</span><b>11~20번과 여섯 글자 해독은 2쪽으로 이어져요.</b>':'<b>게임 시작 화면 → 암호 입력 · 수집 몬스터</b><span>sosoo-defence.vercel.app · 훈련서 '+shortId(s)+' · 출력한 같은 브라우저에서 입력해요.</span>')+'</footer></section>');
 return pages.join('');
}
export function worksheetFocus(s:Worksheet){return s.focus.length?s.focus.map(kindLabel).join(' / '):'기록이 아직 적어 현재 단계의 기본 유형을 골랐어요.';}
